# The following properties are required for (productive) save deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/
MCR.NameOfProject=save
MCR.Metadata.Languages=de,en

##############################################################################
# Mail                                                                       #
##############################################################################
MCR.Mail.Server=
# General sender mail address, e.g. mail@domain
MCR.Mail.Sender=

# Mail for events including self registration, e.g. <name> mail@domain
MCR.mir-module.EditorMail=
# Sender email for events, e.g. <name> mail@domain
MCR.mir-module.MailSender=

##############################################################################
# OAI                                                                        #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.RecordSampleID=
MCR.OAIDataProvider.OAI2.DescriptionURI.EPrints=webapp:oai/oai-eprints.xml
MCR.OAIDataProvider.OAI2.DescriptionURI.Rights=webapp:oai/oai-rights.xml

##############################################################################
# ePuSta                                                                     #
##############################################################################
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

##############################################################################
# Workflow                                                                   #
##############################################################################
MIR.Workflow.Menu=true
MIR.Workflow.Box=true

##############################################################################
# Editor                                                                     #
##############################################################################
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=save.js

##############################################################################
# Disable Servlets                                                           #
##############################################################################
MCR.Servlet.MirSelfRegistrationServlet.Disabled=true
